#!bin/bash


set -o errexit
set -o nounset

execute watchfiles celery.__main__.main \
  --args \
  "-A nerd_api.celery -b \"${CELERY_BROKER}\" flower --basic_auth=\"${CELERY_FLOWER_USR}:${CELERY_FLOWER_PASSWORD}\""


